# Generated by Django 2.2.12 on 2021-06-11 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='ref_image',
            field=models.FileField(default=datetime.datetime(2021, 6, 11, 4, 50, 1, 974202, tzinfo=utc), upload_to='ref_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='src_image',
            field=models.FileField(default=datetime.datetime(2021, 6, 11, 4, 50, 8, 181766, tzinfo=utc), upload_to='src_image/'),
            preserve_default=False,
        ),
    ]
