# Generated by Django 2.2.12 on 2021-06-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210611_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='ref_image',
        ),
    ]
